### ISSUE TITLE
Return a result! :warning:

### ISSUE THREAD

**Issue by iamtheblackunicorn** [iamtheblackunicorn/angelmarkup#1]
Hi, @epage!

I have the following problem: You suggested that I use a different configuration file format for *Acid*. I'm trying to return a result from the `serialize` function in this library and maybe catch errors that may happen during parsing. Any suggestions?

**Comment by epage** [comment]
Could you expand on what you are trying to accomplish and why?  I'm not clear on the case for offering suggestions.

**Comment by epage** [comment]
For a library, `thiserror` is a good way to get up and running to define an error type for your library to return.  If you just want to prototype, you could instead use `anyhow` and switch to `thiserror` later.

**Comment by iamtheblackunicorn** [comment]
@epage Could you perhaps illustrate with an example. I'm afraid I can't picture all that too vividly. 🙈

**Comment by epage** [comment]
I'd recommend looking for resources on this or asking on reddit as that is a more general rust question and I've got some things I need to be focusing on at the moment.

**Comment by iamtheblackunicorn** [comment]
@epage True, true, I thought maybe you had a suggestion. But you are right. I'm gonna dig into this if I can!

**Comment by iamtheblackunicorn** [comment]
@epage Current commit fixes this!❤️
